version: '3.4'

services:
    db:
        container_name: postgres_container_spring
        image: postgres
        environment:
            TZ: America/Sao_Paulo 
            POSTGRES_DB: natiteste
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - nati-network
        restart: always

    nati-teste-backend:
        container_name: nati-teste-backend
        image:  ronaldoalm1812/nati-teste-backend
        restart: always
        build: ./natiteste
        working_dir: /natiteste
        environment: 
            TZ: America/Sao_Paulo
            SPRING_BOOT_ENVIRONMENT: Production
        volumes:
            -  ./natiteste:/natiteste
            - ~/.m2:/root/.m2
        ports:
            - "8081:8081"
        command: mvn clean spring-boot:run
        links:
            - db
        depends_on:
            - db
        networks:
            - nati-network

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            TZ: America/Sao_Paulo
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-teste@gmail.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - nati-network
        depends_on: 
            - nati-teste-backend
        restart: always
networks:
    nati-network:
        driver: bridge
volumes:
    postgres:
    pgadmin: